CREATE TABLE TRANSAC(
ID bigint auto_increment NOT NULL,
NAME VARCHAR(50) NOT NULL,
DETAILS VARCHAR(200),
CASH BOOLEAN NOT NULL,
FLOW VARCHAR(20) NOT NULL,
OUTSTANDING DECIMAL(10,2),
TTIME DATE,
AMOUNT DECIMAL(10,2),
TRANS_TYPE DECIMAL(10,2),
EXIST BOOLEAN NOT NULL,
PRIMARY KEY (ID)
);

